@startuml
title Запрос DELETE /api/v1/sensors/:id для удаления датчика

actor "Специалист компании Тёплый дом" as User
participant "SmartHome" as App

User -> App : DELETE /api/v1/sensors/:id
App -> App : Удаление записи датчика
App --> User : Ответ 200 OK

@enduml