@startuml
title Запрос GET /api/v1/sensors/:id для просмотра информации по датчику

actor "Специалист компании Тёплый дом" as User
participant "SmartHome" as App
participant "Sensor (внешний API)" as ExternalSensor

User -> App : GET /api/v1/sensors/:id
App -> App : Получение датчика из базы данных
alt sensor.Type == models.Temperature
  App -> ExternalSensor : GET /temperature/:id
  ExternalSensor --> App : Актуальное состояние и температура по датчику
end
App --> User : Ответ 200 OK с актуальным состоянием датчика

@enduml